spring:
  application:
    name: metrics-emitter

server:
  port: 7777


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
    jmx:
      domain: 
      exposure:
        include:
        - '*'

        
dummy:
  service:
    key: true