spring:
  application:
    name: metrics-emitter

server:
  port: 7777


management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - metrics
    jmx:
      domain: 
      exposure:
        include:
        - '*'
